# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  external_labels:
    monitor: 'codelab-monitor'

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    scrape_interval: 5s
    static_configs:
    - targets: ['localhost:9090']
   #Details to connect Prometheus with Spring boot actuator end point to scrape the data.
   # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'spring-actuator'
    #Actuator end point to collect the data
    metrics_path: '/actuator/prometheus'
    
    #How frequently to scrape the data from the end points
    scrape_interval: 5s
    
    #target end point
    static_configs:
    - targets: ['localhost:8085']
